services:
  - type: web
    name: hospital-san-pablo
    env: php
    buildCommand: |
      curl -sS https://getcomposer.org/installer | php
      php composer.phar install --optimize-autoloader --no-dev
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:U18P+iDLE2KncuURdpBWE4eksjnvP6eAz54LCtBXVLk=